### ISSUE TITLE
frameworks for self-hosted serving of llm and vector search

### ISSUE THREAD

**Issue by michaelfeil** [oscinis-com/Awesome-LLM-Productization#1]
Got some suggestions for frameworks for self-hosted serving of llm and related.

# Embeddings from OpenAI clip.
Jina
https://github.com/jina-ai/clip-as-service (Apache)

# Text-embeddings:
My own project: infinity ( just add it if you like it)
https://github.com/michaelfeil/infinity (MIT)
https://github.com/huggingface/text-embeddings-inference (no opensource Licence)

# LLM Inference as a service:

Huggingface/ TGI
https://github.com/huggingface/text-generation-inference (no longer opensource licence after 1.0)
Nvidia-TensorRTLLM (Apache2.0)

**Comment by asdfjupyter** [comment]
Thanks @michaelfeil! Will add soon. There are some other papers I noticed and will add over the weekend.

**Comment by asdfjupyter** [comment]
merged. Thanks @michaelfeil!
